/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountInfo: typeof import('./components/AccountInfo.vue')['default']
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    AppTokenSelect: typeof import('./components/AppTokenSelect.vue')['default']
    CreateTokenModal: typeof import('./components/CreateTokenModal.vue')['default']
    DepositModal: typeof import('./components/DepositModal.vue')['default']
    MarketPairs: typeof import('./components/trade/MarketPairs.vue')['default']
    MarketTrades: typeof import('./components/trade/MarketTrades.vue')['default']
    NavDropdown: typeof import('./components/NavDropdown.vue')['default']
    NoSidechainAccountModal: typeof import('./components/NoSidechainAccountModal.vue')['default']
    OpenOrders: typeof import('./components/trade/OpenOrders.vue')['default']
    OrderBook: typeof import('./components/trade/OrderBook.vue')['default']
    OrderForm: typeof import('./components/trade/OrderForm.vue')['default']
    PoolVolumeChart: typeof import('./components/PoolVolumeChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwapWidget: typeof import('./components/trade/SwapWidget.vue')['default']
    TopMovers: typeof import('./components/trade/TopMovers.vue')['default']
    TradeAdvancedWidget: typeof import('./components/trade/TradeAdvancedWidget.vue')['default']
    TradeChart: typeof import('./components/trade/TradeChart.vue')['default']
    TradeTabs: typeof import('./components/trade/TradeTabs.vue')['default']
    TransferModal: typeof import('./components/TransferModal.vue')['default']
  }
}
